// Generated by CoffeeScript 2.3.2
var router;

import Vue from 'vue';

import App from './App.vue';

import Router from 'vue-router';

router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'home',
      component: App
    }
  ]
});

new Vue({
  router: router,
  render: (h) => {
    return h(App);
  }
}).$mount('#app');
